# Makefile for libjvs.
#
# Copyright:	(c) 2007 Jacco van Schaik (jacco@jaccovanschaik.net)
#
# This software is distributed under the terms of the MIT license. See
# http://www.opensource.org/licenses/mit-license.php for details.

.PHONY: tags test

MAKE_ALIB = ar rv
MAKE_SLIB = gcc -shared -o

INSTALL_LIB = /home/jacco/lib
INSTALL_INC = /home/jacco/include/libjvs

CC = gcc

LIBJVS = vector.o buffer.o hash.o list.o dp.o debug.o cx.o \
         utils.o bitmask.o net.o tcp.o udp.o log.o

CFLAGS = -g -fPIC -Wall

all: libjvs.a libjvs.so

libjvs.a: $(LIBJVS)
	$(MAKE_ALIB) libjvs.a $(LIBJVS)

libjvs.so: $(LIBJVS)
	$(MAKE_SLIB) libjvs.so $(LIBJVS)

clean:
	rm -f *.o libjvs.a libjvs.so core vgcore.* libjvs.tgz test-*

libjvs.tgz: clean
	tar cvf - `ls | grep -v libjvs.tgz` | gzip > libjvs.tgz

install: libjvs.a libjvs.so
	if [ ! -d $(INSTALL_LIB) ]; then mkdir -p $(INSTALL_LIB); fi
	cp libjvs.a libjvs.so $(INSTALL_LIB)
	if [ ! -d $(INSTALL_INC)/libjvs ]; then mkdir -p $(INSTALL_INC)/libjvs; fi
	rm -f $(INSTALL_INC)/libjvs/*
	cp *.h $(INSTALL_INC)/libjvs

tags:
	ctags -R .

test: libjvs.a
	for f in `grep -l TEST *.c`; do \
          base=`basename $$f .c`; \
          echo "Testing $$f"; \
          $(CC) $(CFLAGS) -DTEST -o test-$$base $$f libjvs.a -lm; \
          ./test-$$base; \
        done

# Dependencies - generated by deps on Sun Jul 28 14:02:36 CEST 2013

bitmask.o: bitmask.c buffer.h bitmask.h utils.h defs.h 
buffer.o: buffer.c buffer.h utils.h defs.h debug.h 
cx.o: cx.c buffer.h list.h tcp.h udp.h defs.h debug.h cx.h net.h udp.h 
debug.o: debug.c debug.h utils.h 
dp.o: dp.c buffer.h dp.h 
hash.o: hash.c list.h utils.h hash.h 
list.o: list.c list.h 
log.o: log.c udp.h tcp.h list.h defs.h buffer.h log.h 
net.o: net.c defs.h net.h debug.h 
sdr.o: sdr.c defs.h sdr.h 
tcp.o: tcp.c net.h tcp.h debug.h 
udp.o: udp.c net.h tcp.h debug.h utils.h net.h 
utils.o: utils.c defs.h utils.h 
vector.o: vector.c defs.h vector.h 
