# Makefile for libjvs.
#
# Copyright:	(c) 2007 Jacco van Schaik (jacco@jaccovanschaik.net)
#
# This software is distributed under the terms of the MIT license. See
# http://www.opensource.org/licenses/mit-license.php for details.

.PHONY: tags test

MAKE_ALIB = ar rv
MAKE_SLIB = gcc -shared -o

INSTALL_LIB = $(HOME)/lib
INSTALL_INC = $(HOME)/include/libjvs

CC = gcc

LIBJVS = vector.o buffer.o hash.o list.o dp.o debug.o dis.o utils.o \
         bitmask.o net.o tcp.o udp.o log.o ns.o pa.o ml.o options.o geo2d.o

CFLAGS = -std=c99 -D_GNU_SOURCE -g -fPIC -Wall -pedantic -O3 # -DPARANOID

all: libjvs.a libjvs.so

libjvs.a: $(LIBJVS)
	$(MAKE_ALIB) libjvs.a $(LIBJVS)

libjvs.so: $(LIBJVS)
	$(MAKE_SLIB) libjvs.so $(LIBJVS) -lm

clean:
	rm -f *.o libjvs.a libjvs.so core vgcore.* libjvs.tgz *.test *.log

libjvs.tgz: clean
	tar cvf - `ls | grep -v libjvs.tgz` | gzip > libjvs.tgz

install: libjvs.a libjvs.so test
	if [ ! -d $(INSTALL_LIB) ]; then mkdir -p $(INSTALL_LIB); fi
	cp libjvs.a libjvs.so $(INSTALL_LIB)
	if [ ! -d $(INSTALL_INC)/libjvs ]; then mkdir -p $(INSTALL_INC); fi
	rm -rf $(INSTALL_INC)/*
	cp *.h $(INSTALL_INC)

tags:
	ctags -R .

%.test: %.c %.h
	$(CC) $(CFLAGS) -DTEST -o $@ $< libjvs.a -lm

test: do_tests.sh libjvs.a
	./do_tests.sh

# Dependencies - generated by deps on Sun Nov  4 21:20:43 CET 2018

bitmask.o: bitmask.c buffer.h bitmask.h utils.h defs.h 
buffer.o: buffer.c buffer.h utils.h defs.h debug.h 
debug.o: debug.c debug.h utils.h 
dis.o: dis.c list.h debug.h utils.h dis.h dis-types.h 
dp.o: dp.c buffer.h dp.h 
geo2d.o: geo2d.c geo2d.h utils.h 
hash.o: hash.c list.h debug.h utils.h pa.h hash.h 
list.o: list.c list.h 
log.o: log.c net.h udp.h tcp.h list.h defs.h buffer.h log.h 
ml.o: ml.c debug.h defs.h ml.h 
net.o: net.c defs.h net.h debug.h 
ns.o: ns.c net.h tcp.h dis.h utils.h debug.h ns.h ns-types.h utils.h 
options.o: options.c pa.h hash.h buffer.h utils.h options.h 
pa.o: pa.c defs.h debug.h pa.h utils.h 
tcp.o: tcp.c net.h tcp.h defs.h debug.h net.h 
udp.o: udp.c net.h tcp.h debug.h utils.h net.h 
utils.o: utils.c defs.h utils.h buffer.h 
vector.o: vector.c defs.h vector.h 
